language: bash

services:
- docker

env:
  matrix:
  - POSTGRES_VER=11.5 TAGS=11,latest
  - POSTGRES_VER=10.9 TAGS=10
  - POSTGRES_VER=9.6.14 TAGS=9.6,9
  - POSTGRES_VER=9.5.18 TAGS=9.5
  - POSTGRES_VER=9.4.23 TAGS=9.4

script:
- set -e
- make check-configs
- make
- make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
