language: bash

services:
  - docker

env:
  matrix:
    - POSTGRES_VER=11.1 TAGS=11,latest
    - POSTGRES_VER=10.6 TAGS=10
    - POSTGRES_VER=9.6.11 TAGS=9.6,9
    - POSTGRES_VER=9.5.15 TAGS=9.5
    - POSTGRES_VER=9.4.20 TAGS=9.4
    - POSTGRES_VER=9.3.25 TAGS=9.3

script:
  - set -e
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
